name: Execute dealerdup

on:
  #schedule:
    #- cron: "20 22/24 * * *"
  push:
      
 

jobs:
  RunScript:
    runs-on: ubuntu-latest
    concurrency: my-concurrency-group1
    timeout-minutes: 4000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12' # Specify the desired Node.js version
        
    

      - name: Execute SQL Commands
        run: |
          # Install SQL Server command-line tools
          #apt-get update
          #apt-get install -y mssql-tools unixodbc-dev
          # Use a command-line SQL client to execute SQL commands
          sqlcmd -S sql-cars-autotader.database.windows.net -d sqldb-cars-autotrader -U Canvas -P Dut950505 -i dealerdup.sql
          
