name: prop24

on:

  push:
      
 

jobs:
  RunScript:
    runs-on: ubuntu-latest
    concurrency: my-concurrency-group222
    timeout-minutes: 4000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12' # Specify the desired Node.js version
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 pandas sqlalchemy pyodbc  azure-storage-blob regex lxml requests aiohttp asyncio
  
      - name: Install Chrome WebDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver    

      - name: Execute main code
        run: |
          python prop24insid.py
